
export const USER_LOGIN_REQUEST= "USERS_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS= "USERS_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE= "USERS_LOGIN_FAILURE"
export const USER_SIGNUP_REQUEST= "USERS_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS= "USERS_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAILURE= "USERS_SIGNUP_FAILURE"
export const USER_LOGOUT= "USER_LOGOUT"