
export const FETCH_PRODUCTS_START= "FETCH_PRODUCTS_START"
export const FETCH_PRODUCTS_SUCCESS= "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILURE= "FETCH_PRODUCTS_FAILURE"
export const SET_CURRENT_PRODUCT_SUCCESS= "SET_CURRENT_PRODUCT_SUCCESS"
export const REMOVE_CURRENT_PRODUCT_SUCCESS= "REMOVE_CURRENT_PRODUCT_SUCCESS"